# Generated by Django 5.2.7 on 2025-10-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='🚀', max_length=10),
        ),
    ]
