# Generated by Django 5.2.7 on 2025-10-06 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('algorithm', 'Algoritma'), ('programming', 'Programlama'), ('internet', 'İnternet'), ('hardware', 'Donanım'), ('software', 'Yazılım'), ('ai', 'Yapay Zeka'), ('security', 'Güvenlik'), ('history', 'Teknoloji Tarihi')], max_length=20)),
                ('icon', models.CharField(default='💡', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyCardLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cards_read_today', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserCardRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.knowledgecard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('user', 'card')},
            },
        ),
    ]
